### ISSUE TITLE
Task: Setup routing and main components

### ISSUE THREAD

**Issue by alex855k** [CSProjectsEAL/EALAdministrationsProject#23]
## 🏴  Task
Setup basic layout with routing for sub pages using a navigation drawer.

### 1
![image](https://user-images.githubusercontent.com/21573573/55938732-4a8c1b80-5c3c-11e9-8389-7707896f9e39.png)

###### in main component: 
1. Sidebar
2. Page
2.a Header 
3. Footer

### 2 
![image](https://user-images.githubusercontent.com/21573573/55938798-77403300-5c3c-11e9-9ec0-e4f9682fe27a.png)

###### in main component: 

1. Header
1. Sidebar
1. Page  
1. Footer

## Acceptance Criteria
- [ ] Navigation is constantly displayed.

###### On initialization
- [ ] Main component is loaded with all subcomponent and their static content.
- [ ] Load home component.

###### On navigation drawer item press
- [ ] Route to corresponding subcomponent page. 

## Extra info
Use navigation drawer, from vuetify or anything else that you prefer.
https://vuetifyjs.com/en/components/navigation-drawers

For routing use:
https://router.vuejs.org/

**Comment by alex855k** [comment]
Resolved
